"use client"

import React, { useState } from "react"
import Link from "next/link"
import { ArrowRight, ShoppingBag, Laptop, Palmtree } from "lucide-react"

export function DemoSelectorSection() {
    const [hoveredIndex, setHoveredIndex] = useState<number | null>(null)

    const niches = [
        {
            id: "fashion",
            title: "Fashion & Apparel",
            subtitle: "Sifr Style",
            icon: ShoppingBag,
            color: "from-pink-500 to-rose-500",
            image: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&q=80&w=800&h=500",
            link: "/demo/sifr-style"
        },
        {
            id: "tech",
            title: "Gadgets & Electronics",
            subtitle: "Gizmo BD",
            icon: Laptop,
            color: "from-blue-500 to-indigo-500",
            image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&q=80&w=800&h=500",
            link: "/demo/gizmo"
        },
        {
            id: "lifestyle",
            title: "Cosmetics & Lifestyle",
            subtitle: "Glow Needs",
            icon: Palmtree,
            color: "from-emerald-500 to-teal-500",
            image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=800&h=500",
            link: "/demo/glow-needs"
        }
    ]

    return (
        <section className="py-24 md:py-32 bg-white dark:bg-neutral-950">
            <div className="container px-4 md:px-6">
                <div className="flex flex-col items-center text-center justify-center mb-12 lg:mb-20 gap-6">
                    <div className="max-w-3xl mx-auto">
                        <h2 className="text-3xl md:text-5xl font-extrabold tracking-tight mb-4">
                            Explore Live Storefronts
                        </h2>
                        <p className="text-muted-foreground text-lg">
                            Check out these interactive demo stores generated by F-Manager. Add products to the cart and experience the frictionless checkout flow.
                        </p>
                    </div>
                    <Button variant="outline" className="rounded-full font-bold h-12 px-6 neo-card-hover hidden md:inline-flex mt-2" asChild>
                        <Link href="/auth/signin">Claim Your Store <ArrowRight className="ml-2 w-4 h-4" /></Link>
                    </Button>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 lg:gap-8">
                    {niches.map((niche, i) => (
                        <Link
                            key={niche.id}
                            href={niche.link}
                            onMouseEnter={() => setHoveredIndex(i)}
                            onMouseLeave={() => setHoveredIndex(null)}
                            className="group relative block aspect-[4/5] md:aspect-[3/4] rounded-[2rem] overflow-hidden"
                        >
                            {/* Background Image */}
                            <div
                                className="absolute inset-0 bg-cover bg-center transition-transform duration-700 ease-out group-hover:scale-110"
                                style={{ backgroundImage: `url(${niche.image})` }}
                            />

                            {/* Gradient Overlay */}
                            <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/40 to-transparent opacity-80 group-hover:opacity-90 transition-opacity duration-300" />

                            {/* Content */}
                            <div className="absolute inset-0 p-8 flex flex-col justify-end">
                                <div className={`h-12 w-12 rounded-2xl bg-gradient-to-br ${niche.color} flex items-center justify-center mb-6 shadow-lg transform transition-transform duration-500 ${hoveredIndex === i ? '-translate-y-2' : ''}`}>
                                    <niche.icon className="h-6 w-6 text-white" />
                                </div>

                                <h3 className="text-2xl font-bold text-white mb-2 transform transition-transform duration-500">
                                    {niche.title}
                                </h3>

                                <p className="text-neutral-300 font-medium flex items-center mb-6 transform transition-transform duration-500 delay-75">
                                    Demo: {niche.subtitle}
                                </p>

                                {/* Interactive Button */}
                                <div className={`overflow-hidden transition-all duration-500 ease-out ${hoveredIndex === i ? 'max-h-14 opacity-100' : 'max-h-0 opacity-0'}`}>
                                    <div className="inline-flex items-center justify-center h-12 px-6 rounded-full bg-white/20 hover:bg-white text-white hover:text-black backdrop-blur-md transition-colors font-bold text-sm w-full">
                                        Visit Store <ArrowRight className="ml-2 h-4 w-4" />
                                    </div>
                                </div>
                            </div>
                        </Link>
                    ))}
                </div>
            </div>
        </section>
    )
}

import { Button } from "@/components/ui/button"
